name: fluttie
description: Fluttie allows you to easily display stunning Lottie animations in flutter.
version: 0.0.2
author: simolus3 <simolus3@gmail.com>
homepage: https://github.com/flutter/flutter

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.simolus3.fluttie
    pluginClass: FluttiePlugin