name: fluttie
description: Fluttie allows you to easily display stunning Lottie animations in flutter.
version: 0.2.0
author: simolus3 <simolus3@gmail.com>
homepage: https://github.com/simolus3/fluttie

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.simolus3.fluttie
    pluginClass: FluttiePlugin
